version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_event_summary
    restart: unless-stopped
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db


  image_captioning_server:
    build:
      context: ./model_servers/image_captioning_server
      dockerfile: Dockerfile
    container_name: image_captioning_server
    ports:
      - "${IMAGE_CAPTIONING_SERVER_PORT:-8001}:8000"
    environment:
      - DEBUG_MODE=${DEBUG_MODE:-False}
    volumes:
      - ./model_servers/image_captioning_server/app:/app/app
    restart: unless-stopped
    depends_on:
      - mongodb # Though not directly used by this model, good for service startup order

  object_detection_server:
    build:
      context: ./model_servers/object_detection_server
      dockerfile: Dockerfile
    container_name: object_detection_server
    ports:
      - "${OBJECT_DETECTION_SERVER_PORT:-8002}:8000"
    environment:
      - DEBUG_MODE=${DEBUG_MODE:-False}
    volumes:
      - ./model_servers/object_detection_server/app:/app/app
    restart: unless-stopped
    depends_on:
      - mongodb

  text_summarization_server:
    build:
      context: ./model_servers/text_summarization_server
      dockerfile: Dockerfile
    container_name: text_summarization_server
    ports:
      - "${TEXT_SUMMARIZATION_SERVER_PORT:-8003}:8000"
    environment:
      - DEBUG_MODE=${DEBUG_MODE:-False}
    volumes:
      - ./model_servers/text_summarization_server/app:/app/app
    restart: unless-stopped
    depends_on:
      - mongodb

  business_server:
    build:
      context: ./business_server
      dockerfile: Dockerfile
    container_name: business_server
    ports:
      - "${BUSINESS_SERVER_PORT:-8000}:8000"
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - IMAGE_CAPTIONING_URL=http://image_captioning_server:8000/caption/
      - OBJECT_DETECTION_URL=http://object_detection_server:8000/detect/
      - TEXT_SUMMARIZATION_URL=http://text_summarization_server:8000/generate/
      - DEBUG_MODE=${DEBUG_MODE:-False}
      - MAX_SUMMARIES_PER_DAY=${MAX_SUMMARIES_PER_DAY:-20}
      - MAX_PARTICIPATION_WITH_SHARES=${MAX_PARTICIPATION_WITH_SHARES:-4}
    volumes:
      - ./business_server/app:/app/app
      - ./tests/sample_images:/sample_images # For test client access if run from within container or for business server to load local files if needed
    restart: unless-stopped
    depends_on:
      - mongodb
      - image_captioning_server
      - object_detection_server
      - text_summarization_server

volumes:
  mongodb_data:
    driver: local 